// The server's database: every piece of state it keeps — accounts, settings,
// keys, sessions, transcripts, the usage ledger — lives here. Only real files
// (workspaces, sandbox homes) stay on disk.
//
// SQLite is the default, in the data directory; PostgreSQL is the alternative.
// Both are reached through database/sql with hand-written SQL kept to the
// common subset of the two: "?" placeholders (rewritten to $n for PostgreSQL),
// TEXT / BIGINT / INTEGER / DOUBLE PRECISION columns, INSERT … ON CONFLICT for
// upserts, keys generated by the application. Times are stored as UTC Unix
// nanoseconds: comparable and sortable the same way in both.
//
// The server is single-instance: its running turns, sandboxes and caches live
// in memory, so a second process on the same database would diverge. Opening
// the database takes an instance lock, and a second process is refused.
package main

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "modernc.org/sqlite"
)

type sqlDialect int

const (
	dialectSQLite sqlDialect = iota
	dialectPostgres
)

func (d sqlDialect) String() string {
	if d == dialectPostgres {
		return "postgres"
	}
	return "sqlite"
}

// dbTarget is a parsed -db value.
type dbTarget struct {
	dialect sqlDialect
	// path is the SQLite file; dsn the PostgreSQL connection string.
	path string
	dsn  string
}

// parseDBTarget reads a -db value: "sqlite:<path>" (sqlite:///abs/pigo.db or
// sqlite:pigo.db, relative to dataDir), a bare path (taken as SQLite), or a
// postgres:// / postgresql:// URL. Empty means <dataDir>/pigo.db.
func parseDBTarget(raw, dataDir string) (dbTarget, error) {
	raw = strings.TrimSpace(raw)
	switch {
	case raw == "":
		return dbTarget{dialect: dialectSQLite, path: filepath.Join(dataDir, "pigo.db")}, nil
	case strings.HasPrefix(raw, "postgres://"), strings.HasPrefix(raw, "postgresql://"):
		return dbTarget{dialect: dialectPostgres, dsn: raw}, nil
	case strings.Contains(raw, "://") && !strings.HasPrefix(raw, "sqlite://"):
		return dbTarget{}, fmt.Errorf("unsupported database %q: use sqlite:<path> or postgres://…", redactDSN(raw))
	}
	path := strings.TrimPrefix(strings.TrimPrefix(raw, "sqlite://"), "sqlite:")
	if path == "" {
		return dbTarget{}, errors.New("sqlite: empty path")
	}
	if !filepath.IsAbs(path) {
		path = filepath.Join(dataDir, path)
	}
	return dbTarget{dialect: dialectSQLite, path: path}, nil
}

// String describes the target for logs, without a password.
func (t dbTarget) String() string {
	if t.dialect == dialectPostgres {
		return "postgres " + redactDSN(t.dsn)
	}
	return "sqlite " + t.path
}

func redactDSN(raw string) string {
	u, err := url.Parse(raw)
	if err != nil || u.User == nil {
		return raw
	}
	if _, has := u.User.Password(); has {
		u.User = url.UserPassword(u.User.Username(), "xxxxx")
	}
	return u.String()
}

// sqlDB is the opened database.
type sqlDB struct {
	db      *sql.DB
	dialect sqlDialect
	target  dbTarget
	// unlock releases the instance lock.
	unlock func()
}

// openDB opens target, takes the instance lock and brings the schema up to
// date.
func openDB(target dbTarget) (*sqlDB, error) {
	var (
		db  *sql.DB
		err error
	)
	switch target.dialect {
	case dialectSQLite:
		if err := os.MkdirAll(filepath.Dir(target.path), 0o700); err != nil {
			return nil, fmt.Errorf("create database dir: %w", err)
		}
		dsn := "file:" + target.path +
			"?_pragma=busy_timeout(5000)&_pragma=journal_mode(WAL)&_pragma=synchronous(NORMAL)&_pragma=foreign_keys(1)"
		db, err = sql.Open("sqlite", dsn)
		if err != nil {
			return nil, fmt.Errorf("open %s: %w", target, err)
		}
		// One connection: writes are serialized, so there is no SQLITE_BUSY to
		// handle. The rule that follows is that a query's rows must be read to
		// the end before the next statement, and a transaction's statements
		// must go through the transaction — see query and inTx.
		db.SetMaxOpenConns(1)
	case dialectPostgres:
		db, err = sql.Open("pgx", target.dsn)
		if err != nil {
			return nil, fmt.Errorf("open %s: %w", target, err)
		}
		db.SetMaxOpenConns(10)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	if err := db.PingContext(ctx); err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("connect %s: %w", target, err)
	}
	d := &sqlDB{db: db, dialect: target.dialect, target: target, unlock: func() {}}
	if err := d.lockInstance(); err != nil {
		_ = db.Close()
		return nil, err
	}
	if err := d.upgradeSchema(); err != nil {
		d.Close()
		return nil, fmt.Errorf("upgrade schema: %w", err)
	}
	return d, nil
}

// errDBInUse reports the instance lock held by another process.
var errDBInUse = errors.New("另一个 pigo-server 进程正在使用这个数据库（本服务只支持单实例运行）")

// lockInstance takes the single-instance lock: an exclusive flock beside the
// SQLite file, or a PostgreSQL advisory lock held on a dedicated connection.
// The advisory lock is keyed by the schema, so separate schemas (tests) do not
// collide.
func (d *sqlDB) lockInstance() error {
	switch d.dialect {
	case dialectSQLite:
		f, err := os.OpenFile(d.target.path+".lock", os.O_CREATE|os.O_RDWR, 0o600)
		if err != nil {
			return fmt.Errorf("open instance lock: %w", err)
		}
		if err := syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
			_ = f.Close()
			return errDBInUse
		}
		d.unlock = func() {
			_ = syscall.Flock(int(f.Fd()), syscall.LOCK_UN)
			_ = f.Close()
		}
	case dialectPostgres:
		ctx := context.Background()
		conn, err := d.db.Conn(ctx)
		if err != nil {
			return fmt.Errorf("instance lock connection: %w", err)
		}
		var got bool
		if err := conn.QueryRowContext(ctx, "SELECT pg_try_advisory_lock(hashtext('pigo-server:' || current_schema()))").Scan(&got); err != nil {
			_ = conn.Close()
			return fmt.Errorf("instance lock: %w", err)
		}
		if !got {
			_ = conn.Close()
			return errDBInUse
		}
		// Closing the connection ends the session, which releases the lock.
		d.unlock = func() { _ = conn.Close() }
	}
	return nil
}

// Close releases the instance lock and the connections.
func (d *sqlDB) Close() {
	if d == nil {
		return
	}
	d.unlock()
	_ = d.db.Close()
}

// rebind rewrites "?" placeholders for the dialect. The SQL in this package
// never has a "?" inside a string literal.
func (d *sqlDB) rebind(query string) string {
	if d.dialect != dialectPostgres || !strings.Contains(query, "?") {
		return query
	}
	var b strings.Builder
	n := 0
	for _, r := range query {
		if r == '?' {
			n++
			fmt.Fprintf(&b, "$%d", n)
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// sqlExec is what a statement runs on: the database, or a transaction.
type sqlExec interface {
	exec(query string, args ...any) (sql.Result, error)
	query(query string, scan func(*sql.Rows) error, args ...any) error
}

func (d *sqlDB) exec(query string, args ...any) (sql.Result, error) {
	return d.db.Exec(d.rebind(query), args...)
}

// query runs a query and calls scan for each row, reading every row before it
// returns — so with SQLite's single connection nothing is left holding it.
func (d *sqlDB) query(query string, scan func(*sql.Rows) error, args ...any) error {
	rows, err := d.db.Query(d.rebind(query), args...)
	if err != nil {
		return err
	}
	return scanAll(rows, scan)
}

// count runs a SELECT COUNT(*)-style query.
func (d *sqlDB) count(query string, args ...any) (int, error) {
	var n int
	err := d.db.QueryRow(d.rebind(query), args...).Scan(&n)
	return n, err
}

func scanAll(rows *sql.Rows, scan func(*sql.Rows) error) error {
	defer rows.Close()
	for rows.Next() {
		if err := scan(rows); err != nil {
			return err
		}
	}
	return rows.Err()
}

type sqlTx struct {
	tx *sql.Tx
	d  *sqlDB
}

func (t *sqlTx) exec(query string, args ...any) (sql.Result, error) {
	return t.tx.Exec(t.d.rebind(query), args...)
}

func (t *sqlTx) query(query string, scan func(*sql.Rows) error, args ...any) error {
	rows, err := t.tx.Query(t.d.rebind(query), args...)
	if err != nil {
		return err
	}
	return scanAll(rows, scan)
}

// inTx runs fn in a transaction, committing if it returns nil. Inside fn every
// statement must go through tx: with SQLite's single connection, a statement
// on the database itself would wait for the transaction forever.
func (d *sqlDB) inTx(fn func(tx *sqlTx) error) error {
	tx, err := d.db.Begin()
	if err != nil {
		return err
	}
	if err := fn(&sqlTx{tx: tx, d: d}); err != nil {
		_ = tx.Rollback()
		return err
	}
	return tx.Commit()
}

// --- value conversions ------------------------------------------------------------

func toNanos(t time.Time) int64 {
	if t.IsZero() {
		return 0
	}
	return t.UTC().UnixNano()
}

func fromNanos(n int64) time.Time {
	if n == 0 {
		return time.Time{}
	}
	return time.Unix(0, n).UTC()
}

func nullNanos(t *time.Time) sql.NullInt64 {
	if t == nil || t.IsZero() {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: t.UTC().UnixNano(), Valid: true}
}

func fromNullNanos(n sql.NullInt64) *time.Time {
	if !n.Valid {
		return nil
	}
	t := time.Unix(0, n.Int64).UTC()
	return &t
}

func boolInt(b bool) int {
	if b {
		return 1
	}
	return 0
}
